### ISSUE TITLE
More efficient way to do topic modeling with pandas?

### ISSUE THREAD

**Issue by jccf12** [jccf12/career_village_challenge#2]
From @DarthQadir:
Added function for topic modeling. Looking for ideas @MoGaber as to how I can run this topic modeling function on each question's body efficiently, then append any newly found tags to the professional dataset (basically it should find 2 topics for each question, then find the professionals who answered that question, then add these new tags to the 'prev_q_tags' column for the professionals who answered the database.

**Comment by MoGaber** [comment]
Look for "apply_function" for the detailed answer at the bottom of the notebook
